// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefTk = `-- name: CreateRefTk :one
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    NOW() + INTERVAL '60 days'
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateRefTkParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) CreateRefTk(ctx context.Context, arg CreateRefTkParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefTk, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_tokens
WHERE token = $1 LIMIT 1
`

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateRevokeAt = `-- name: UpdateRevokeAt :exec
UPDATE refresh_tokens
SET updated_at = $2, revoked_at = $2
WHERE token = $1
`

type UpdateRevokeAtParams struct {
	Token     string
	UpdatedAt time.Time
}

func (q *Queries) UpdateRevokeAt(ctx context.Context, arg UpdateRevokeAtParams) error {
	_, err := q.db.ExecContext(ctx, updateRevokeAt, arg.Token, arg.UpdatedAt)
	return err
}
